### ISSUE TITLE
How do I specify the database located in dokuwiki?

### ISSUE THREAD

**Issue by execonic** [gkrid/dokuwiki-plugin-sql2wiki#1]
The code I entered:
`<sql2wiki db="data_pageinfo" query="SELECT * from data_pageinfo"> </sql2wiki>`
The error I got:
![image](https://user-images.githubusercontent.com/27429124/233534214-e8a10cef-f78d-4bf9-99d0-9f39b881244b.png)

Thanks.

**Comment by solewniczak** [comment]
To use the plugin, you need an upgraded version of sqlite plugin, which is still in devel stage. You can download it from here: https://github.com/gkrid/sqlite/archive/refs/heads/devel.zip. The query="" parameter defines the name of the query. With the upgraded version of sqlite plugin, you can create so-called "named queries" and this is the feature this plugin relays on.

**Comment by execonic** [comment]
> The query="" parameter defines the name of the query. With the upgraded version of sqlite plugin, you can create so-called "named queries" and this is the feature this plugin relays on.

I'm still confused about the `db` parameter. Do you mean that there is no need to specify the "db" parameter as the plugin will select the database correctly after I upgrade `sqlite`?

**Comment by solewniczak** [comment]
No. The db parameter is requires since there can be many sqlite databases in dokuwiki. For example plugins like struct, approve and ireadit create their own databases which usually have the same name as the plugins. Looking on the example you provided, I believe you trying to use the sql2wiki plugin with the struct plugin. If you do, the syntax will be something like this:
`
 <sql2wiki db="struct" query="the_saved_query_name"> </sql2wiki>`

**Comment by execonic** [comment]
Yeah, I got it. Thank you very much.
